# osiris: this file has lots of implications
"""
Django settings for osiris_project project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&d_o3btz+953y454f1ak5nhvg8kv292f5m7@%5$kne0=#^s-eq'

# Osiris: the key is unique for each project, 
# Osiris: the guy in the video added an "a" to the key, not sure why he did that

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Osiris: The bug is very useful when learning or developing.
# Osiris: If the server is used by real people (a "live server"), 
# Osiris: it should be turned into False. 

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my own apps
    'products',
    'pages'
]

# Osiris: Installed apps are apps installed by default. Also  I can build my own apps/products 
# Osiris: (apps are components, not the apps of your mobile phone).
# Osiris: Apps are little pieces of the gretare project django itself
# Osiris: If I go into my project (using the link given when activate) 
# Osiris: and type "/admin", it directs me to the "django administration project"
# Osiris: Nota: usar dos ventanas de terminal, una para correr el servidor y 
# Osiris: otra para moverme entre carpetas del proyecto

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Osiris: This middleware consists in a lot of security features

ROOT_URLCONF = 'osiris_project.urls'

# Osiris: this root_urlconf is a buid_in function and gives the link to the project
# Osiris: or something like that 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")], #This was added so django can access to templates folder
        'APP_DIRS': True,                              #independientemente de si estás con cfe o no
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Osiris: the templates are associated with the html (not sure). See later

WSGI_APPLICATION = 'osiris_project.wsgi.application'

# Osiris: This is how the server works, it goes through and uses this setting, 
# Osiris: you can change it or not. 

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         


# Osiris: the databases, django maps to db really well, mySQL, postgreSQL and others.
# Osiris: If you want to use a different program for db, you can change some of the settings. 
# Osiris: By default sqlite is used

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Osiris: this validates the passwords.

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Osiris: This internacionalization stuff, Later

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# Osiris: STATIC is associated to where you store images, javascript, your css, etc.